name: Subdomain Recon Workflow for IAC

on: [push]

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Git and configure user
        run: |
          git config --global user.name "ASEEMYASH007"
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
      
      - name: Download Subfinder
        run: |
          mkdir -p /home/runner/configz/subfinder
          cp provider-config.yaml /home/runner/configz/subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.7/subfinder_2.6.7_linux_amd64.zip
          unzip subfinder_2.6.7_linux_amd64.zip
          sudo chmod +x subfinder

      - name: Run Subfinder
        run: |
          echo -e "iac.com" > iac_scope.txt
          ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -dL iac_scope.txt -recursive -o iac_subs.txt
          wc -l iac_subs.txt
          git add iac_subs.txt
          git commit -m 'Add Subfinder results for IAC'
          git push

      - name: Run crtsh.py
        run: |
          python3 ./crtsh.py -d "iac.com" -r -w >> iac_crtsh_domains.txt
          wc -l iac_crtsh_domains.txt
          git add iac_crtsh_domains.txt
          git commit -m 'Add crtsh.py results for IAC'
          git push

      - name: Combine Subfinder and crtsh results
        run: |
          sort -u iac_subs.txt iac_crtsh_domains.txt > iac_final1.txt
          wc -l iac_final1.txt
          git add iac_final1.txt
          git commit -m 'Combine Subfinder and crtsh results for IAC'
          git push

      - name: Fetch Additional Sources
        run: |
          xargs -a iac_scope.txt -I {} sh -c 'curl -s "https://jldc.me/anubis/subdomains/{}" | tr -d "[]\"" | tr "," "\n" >> jldc.txt'
          xargs -a iac_scope.txt -I {} sh -c 'curl -s "https://api.subdomain.center/?domain={}" | tr -d "[]\"" | tr "," "\n" >> subcenter.txt'
          xargs -a iac_scope.txt -I {} sh -c 'curl -s "https://api.hackertarget.com/hostsearch/?q={}" | cut -d"," -f1 >> hackertarget.txt'
          sudo chmod +x *
          ./alienvault_hostnamefetcher.sh "iac.com" iac_alienvault.txt
          python3 ./merklemap2subscan.py -d "iac.com" -o iac_merkle.txt -t 5

      - name: Combine Additional Source Results
        run: |
          sort -u subcenter.txt hackertarget.txt iac_alienvault.txt jldc.txt iac_merkle.txt > iac_combined_domains.txt
          wc -l iac_combined_domains.txt
          git add iac_combined_domains.txt iac_merkle.txt
          git commit -m 'Combine additional source results for IAC'
          git push

      - name: Download Amazon Domains
        run: curl -o amazon_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/amazon/ipv4_merged_sni.txt

      - name: Download Oracle Domains
        run: curl -o oracle_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/oracle/ipv4_merged_sni.txt

      - name: Download DigitalOcean Domains
        run: curl -o digitalocean_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/digitalocean/ipv4_merged_sni.txt

      - name: Download Google Domains
        run: curl -o google_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/google/ipv4_merged_sni.txt

      - name: Download Microsoft Domains
        run: curl -o microsoft_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/microsoft/ipv4_merged_sni.txt

      - name: Concatenate All Domains
        run: cat amazon_domains.NAYA.txt oracle_domains.NAYA.txt digitalocean_domains.NAYA.txt google_domains.NAYA.txt microsoft_domains.NAYA.txt > all_domains.NAYA.txt

      - name: Filter for Specific Domains and Subdomains Entries
        run: |
          grep -Eo '\b(\S+\.)?(iac\.com)\b' all_domains.NAYA.txt | tr ' ' '\n' | sort -u > iac_cloud_domains.txt
          wc -l iac_cloud_domains.txt

      - name: Commit and Push Filtered Domains
        run: |
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
          git config --global user.name "ASEEMYASH007"
          git add iac_cloud_domains.txt
          git commit -m "Add processed IAC domains"
          git push

      - name: Combine All Results
        run: |
          sort -u iac_final1.txt iac_combined_domains.txt iac_cloud_domains.txt > iac_final_results.txt
          wc -l iac_final_results.txt
          git add iac_final_results.txt
          git commit -m 'Combine all results for IAC'
          git push

      - name: Clean Wildcard Domains
        run: |
          sed 's/^\*\.\(.*\)$/\1/' iac_final_results.txt > iac_final_results_cleaned.txt
          wc -l iac_final_results_cleaned.txt
          git add iac_final_results_cleaned.txt
          git commit -m "Cleaned wildcard domains in final results"
          git push
