name: Subdomain Recon Workflow for Wells Fargo Company

on: [push]

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Git and configure user
        run: |
          git config --global user.name "ASEEMYASH007"
          git config --global user.email "21btrcc007@jainuniversity.ac.in"

      - name: Download Subfinder
        run: |
          mkdir -p /home/runner/configz/subfinder
          cp provider-config.yaml /home/runner/configz/subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.6/subfinder_2.6.6_linux_amd64.zip
          unzip subfinder_2.6.6_linux_amd64.zip
          sudo chmod +x *

      - name: Run subfinder
        run: |
          echo -e "wellsfargo.com" > wellsfargo_company_scope.txt
          ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -dL wellsfargo_company_scope.txt -recursive -o wellsfargo_company_subs.txt
          wc -l wellsfargo_company_subs.txt
          git add wellsfargo_company_subs.txt
          git commit -m 'Add subfinder results for Wells Fargo company'
          git push

      - name: Run crtsh.py
        run: |
          python3 ./crtsh.py -d "wellsfargo.com" -r -w >> wellsfargo_company_crtsh_domains.txt
          wc -l wellsfargo_company_crtsh_domains.txt
          git add wellsfargo_company_crtsh_domains.txt
          git commit -m 'Add crtsh.py results for Wells Fargo company'
          git push

      - name: Combine subfinder and crtsh results
        run: |
          sort -u wellsfargo_company_subs.txt wellsfargo_company_crtsh_domains.txt > wellsfargo_final1.txt
          wc -l wellsfargo_final1.txt
          git add wellsfargo_final1.txt
          git commit -m 'Combine subfinder and crtsh results for Wells Fargo company'
          git push

      - name: Fetch additional sources
        run: |
          xargs -a wellsfargo_company_scope.txt -I {} sh -c 'curl -s "https://jldc.me/anubis/subdomains/{}" | tr -d "[]\"" | tr "," "\n" >> jldc.txt'
          xargs -a wellsfargo_company_scope.txt -I {} sh -c 'curl -s "https://api.subdomain.center/?domain={}" | tr -d "[]\"" | tr "," "\n" >> subcenter.txt'
          xargs -a wellsfargo_company_scope.txt -I {} sh -c 'curl -s "https://api.hackertarget.com/hostsearch/?q={}" | cut -d"," -f1 >> hackertarget.txt'
          sudo chmod +x *
          ./alienvault_hostnamefetcher.sh "wellsfargo.com" wellsfargo_company_alienvault.txt
          python3 ./merklemap2subscan.py -d "wellsfargo.com" -o wellsfargo_company_merkle.txt -t 5

      - name: Combine additional source results
        run: |
          sort -u subcenter.txt hackertarget.txt wellsfargo_company_alienvault.txt jldc.txt wellsfargo_company_merkle.txt > wellsfargo_company_combined_domains.txt
          wc -l wellsfargo_company_combined_domains.txt
          git add wellsfargo_company_combined_domains.txt wellsfargo_company_merkle.txt
          git commit -m 'Combine additional source results for Wells Fargo company'
          git push

      - name: Download Amazon domains
        run: curl -o amazon_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/amazon/ipv4_merged_sni.txt

      - name: Download Oracle domains
        run: curl -o oracle_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/oracle/ipv4_merged_sni.txt

      - name: Download DigitalOcean domains
        run: curl -o digitalocean_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/digitalocean/ipv4_merged_sni.txt

      - name: Download Google domains
        run: curl -o google_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/google/ipv4_merged_sni.txt

      - name: Download Microsoft domains
        run: curl -o microsoft_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/microsoft/ipv4_merged_sni.txt

      - name: Concatenate all domains
        run: cat amazon_domains.NAYA.txt oracle_domains.NAYA.txt digitalocean_domains.NAYA.txt google_domains.NAYA.txt microsoft_domains.NAYA.txt > all_domains.NAYA.txt

      - name: Filter for specific domains and subdomains entries
        run: |
          grep -Eo '\b(\S+\.)?(wellsfargo\.com)\b' all_domains.NAYA.txt | sed 's/\[//g' | sed 's/\]//g' | tr ' ' '\n' > wellsfargo_company_cloud_domains.txt
          wc -l wellsfargo_company_cloud_domains.txt

      - name: Commit and push filtered domains
        run: |
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
          git config --global user.name "ASEEMYASH007"
          git add wellsfargo_company_cloud_domains.txt
          git commit -m "Add processed Wells Fargo company domains"
          git push

      - name: Combine all results
        run: |
          sort -u wellsfargo_final1.txt wellsfargo_company_combined_domains.txt wellsfargo_company_cloud_domains.txt > wellsfargo_company_final_results.txt
          wc -l wellsfargo_company_final_results.txt
          git add wellsfargo_company_final_results.txt
          git commit -m 'Combine all results for Wells Fargo company'
          git push

      - name: Clean wildcard domains
        run: |
          sed 's/^\*\.\(.*\)$/\1/' wellsfargo_company_final_results.txt > wellsfargo_final_results_cleaned.txt
          wc -l wellsfargo_final_results_cleaned.txt
          git add wellsfargo_final_results_cleaned.txt
          git commit -m "Cleaned wildcard domains in final results"
          git push

      - name: Validate DNS records for subdomains
        run: |
          touch valid_wellsfargo_subdomains.txt
          while read -r domain; do
            if host "$domain" &> /dev/null; then
              echo "$domain" >> valid_wellsfargo_subdomains.txt
            fi
          done < wellsfargo_final_results_cleaned.txt
          wc -l valid_wellsfargo_subdomains.txt
          git add valid_wellsfargo_subdomains.txt
          git commit -m "Add valid DNS subdomains for Wells Fargo"
          git push
