name: Subdomain Recon Workflow

on: [push]

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Git and configure user
        run: |
          git config --global user.name "aseemyash"
          git config --global user.email "aseemyash98@gmail.com"

      - name: Download Subfinder
        run: |
          mkdir -p /home/runner/configz/subfinder
          cp provider-config.yaml /home/runner/configz/subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.6/subfinder_2.6.6_linux_amd64.zip
          unzip subfinder_2.6.6_linux_amd64.zip
          sudo chmod +x *

      - name: Run subfinder
        run: |
          echo -e "capcut.com\nbyteplus.com\ncapcutapi.com\nfaceueditor.com" > bytedance_scope.txt
          ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -dL bytedance_scope.txt -o bytedance_subs.txt
          wc -l bytedance_subs.txt
          git add bytedance_subs.txt
          git commit -m 'Add subfinder results for ByteDance'
          git push

      - name: Run crtsh.py
        run: |
          xargs -a bytedance_scope.txt -I {} python3 ./crtsh.py -d {} -r -w >> bytedance_crtsh_domains.txt
          wc -l bytedance_crtsh_domains.txt
          git add bytedance_crtsh_domains.txt
          git commit -m 'Add crtsh.py results for ByteDance'
          git push

      - name: Combine subfinder and crtsh results
        run: |
          sort -u bytedance_subs.txt bytedance_crtsh_domains.txt > bytedance_final1.txt
          wc -l bytedance_final1.txt
          git add bytedance_final1.txt
          git commit -m 'Combine subfinder and crtsh results for ByteDance'
          git push

      - name: Fetch additional sources
        run: |
          xargs -a bytedance_scope.txt -I {} sh -c 'curl -s "https://jldc.me/anubis/subdomains/{}" | tr -d "[]\"" | tr "," "\n" >> jldc.txt'
          xargs -a bytedance_scope.txt -I {} sh -c 'curl -s "https://api.subdomain.center/?domain={}" | tr -d "[]\"" | tr "," "\n" >> subcenter.txt'
          xargs -a bytedance_scope.txt -I {} sh -c 'curl -s "https://api.hackertarget.com/hostsearch/?q={}" | cut -d"," -f1 >> hackertarget.txt'
          sudo chmod +x *
          ./alienvault_hostnamefetcher.sh "capcut.com,byteplus.com,capcutapi.com,faceueditor.com" bytedance_alienvault.txt
          python3 ./merklemap2subscan.py -d capcut.com,byteplus.com,capcutapi.com,faceueditor.com -o bytedance_merkle.txt -t 5

      - name: Combine additional source results
        run: |
          sort -u subcenter.txt hackertarget.txt bytedance_alienvault.txt jldc.txt bytedance_merkle.txt > bytedance_combined_domains.txt
          wc -l bytedance_combined_domains.txt
          git add bytedance_combined_domains.txt bytedance_merkle.txt
          git commit -m 'Combine additional source results for ByteDance'
          git push

      - name: Download Amazon domains
        run: curl -o amazon_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/amazon/ipv4_merged_sni.txt

      - name: Download Oracle domains
        run: curl -o oracle_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/oracle/ipv4_merged_sni.txt

      - name: Download DigitalOcean domains
        run: curl -o digitalocean_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/digitalocean/ipv4_merged_sni.txt

      - name: Download Google domains
        run: curl -o google_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/google/ipv4_merged_sni.txt

      - name: Download Microsoft domains
        run: curl -o microsoft_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/microsoft/ipv4_merged_sni.txt

      - name: Concatenate all domains
        run: cat amazon_domains.NAYA.txt oracle_domains.NAYA.txt digitalocean_domains.NAYA.txt google_domains.NAYA.txt microsoft_domains.NAYA.txt > all_domains.NAYA.txt

      - name: Filter for specific domains and subdomains entries
        run: |
          grep -Eo '\b(\S+\.)?(capcut\.com|byteplus\.com|capcutapi\.com|faceueditor\.com)\b' all_domains.NAYA.txt | sed 's/\[//g' | sed 's/\]//g' | tr ' ' '\n' > bytedance_cloud_domains.txt
          wc -l bytedance_cloud_domains.txt

      - name: Commit and push filtered domains
        run: |
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
          git config --global user.name "aseemyashuniversity"
          git add bytedance_cloud_domains.txt
          git commit -m "Add processed ByteDance domains"
          git push

      - name: Combine all results
        run: |
          sort -u bytedance_final1.txt bytedance_combined_domains.txt bytedance_cloud_domains.txt > bytedance_final_results.txt
          wc -l bytedance_final_results.txt
          git add bytedance_final_results.txt
          git commit -m 'Combine all results for ByteDance'
          git push
