name: Subdomain Recon Workflow for Bentley

on: [push]

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Git and configure user
        run: |
          git config --global user.name "ASEEMYASH007"
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
      
      - name: Download Subfinder
        run: |
          mkdir -p /home/runner/configz/subfinder
          cp provider-config.yaml /home/runner/configz/subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.7/subfinder_2.6.7_linux_amd64.zip
          unzip subfinder_2.6.7_linux_amd64.zip
          sudo chmod +x subfinder

      - name: Run Subfinder
        run: |
          echo -e "bentley.com\nblyncsy.com\ncesium.com\neasypower.com\neagle.io\npowerlinesystems.com\nspidasoftware.com\ninfrastructureiot.com\nsensemetrics.com\nvdvcloud.com" > bentley_scope.txt
          ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -dL bentley_scope.txt -recursive -o bentley_subs.txt
          wc -l bentley_subs.txt
          git add bentley_subs.txt
          git commit -m 'Add Subfinder results for Bentley'
          git push

      - name: Run crtsh.py
        run: |
          python3 ./crtsh.py -d "bentley.com,blyncsy.com,cesium.com,easypower.com,eagle.io,powerlinesystems.com,spidasoftware.com,infrastructureiot.com,sensemetrics.com,vdvcloud.com" -r -w >> bentley_crtsh_domains.txt
          wc -l bentley_crtsh_domains.txt
          git add bentley_crtsh_domains.txt
          git commit -m 'Add crtsh.py results for Bentley'
          git push

      - name: Combine Subfinder and crtsh results
        run: |
          sort -u bentley_subs.txt bentley_crtsh_domains.txt > bentley_final1.txt
          wc -l bentley_final1.txt
          git add bentley_final1.txt
          git commit -m 'Combine Subfinder and crtsh results for Bentley'
          git push

      - name: Fetch Additional Sources
        run: |
          xargs -a bentley_scope.txt -I {} sh -c 'curl -s "https://jldc.me/anubis/subdomains/{}" | tr -d "[]\"" | tr "," "\n" >> jldc.txt'
          xargs -a bentley_scope.txt -I {} sh -c 'curl -s "https://api.subdomain.center/?domain={}" | tr -d "[]\"" | tr "," "\n" >> subcenter.txt'
          xargs -a bentley_scope.txt -I {} sh -c 'curl -s "https://api.hackertarget.com/hostsearch/?q={}" | cut -d"," -f1 >> hackertarget.txt'
          sudo chmod +x *
          ./alienvault_hostnamefetcher.sh "bentley.com,blyncsy.com,cesium.com,easypower.com,eagle.io,powerlinesystems.com,spidasoftware.com,infrastructureiot.com,sensemetrics.com,vdvcloud.com" bentley_alienvault.txt
          python3 ./merklemap2subscan.py -d bentley.com,blyncsy.com,cesium.com,easypower.com,eagle.io,powerlinesystems.com,spidasoftware.com,infrastructureiot.com,sensemetrics.com,vdvcloud.com -o bentley_merkle.txt -t 5

      - name: Combine Additional Source Results
        run: |
          sort -u subcenter.txt hackertarget.txt bentley_alienvault.txt jldc.txt bentley_merkle.txt > bentley_combined_domains.txt
          wc -l bentley_combined_domains.txt
          git add bentley_combined_domains.txt bentley_merkle.txt
          git commit -m 'Combine additional source results for Bentley'
          git push

      - name: Download Amazon Domains
        run: curl -o amazon_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/amazon/ipv4_merged_sni.txt

      - name: Download Oracle Domains
        run: curl -o oracle_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/oracle/ipv4_merged_sni.txt

      - name: Download DigitalOcean Domains
        run: curl -o digitalocean_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/digitalocean/ipv4_merged_sni.txt

      - name: Download Google Domains
        run: curl -o google_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/google/ipv4_merged_sni.txt

      - name: Download Microsoft Domains
        run: curl -o microsoft_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/microsoft/ipv4_merged_sni.txt

      - name: Concatenate All Domains
        run: cat amazon_domains.NAYA.txt oracle_domains.NAYA.txt digitalocean_domains.NAYA.txt google_domains.NAYA.txt microsoft_domains.NAYA.txt > all_domains.NAYA.txt

      - name: Filter for Specific Domains and Subdomains Entries
        run: |
          grep -Eo '\b(\S+\.)?(bentley\.com|blyncsy\.com|cesium\.com|easypower\.com|eagle\.io|powerlinesystems\.com|spidasoftware\.com|infrastructureiot\.com|sensemetrics\.com|vdvcloud\.com)\b' all_domains.NAYA.txt | tr ' ' '\n' | sort -u > bentley_cloud_domains.txt
          wc -l bentley_cloud_domains.txt

      - name: Commit and Push Filtered Domains
        run: |
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
          git config --global user.name "ASEEMYASH007"
          git add bentley_cloud_domains.txt
          git commit -m "Add processed Bentley domains"
          git push

      - name: Combine All Results
        run: |
          sort -u bentley_final1.txt bentley_combined_domains.txt bentley_cloud_domains.txt > bentley_final_results.txt
          wc -l bentley_final_results.txt
          git add bentley_final_results.txt
          git commit -m 'Combine all results for Bentley'
          git push

      - name: Clean Wildcard Domains
        run: |
          sed 's/^\*\.\(.*\)$/\1/' bentley_final_results.txt > bentley_final_results_cleaned.txt
          wc -l bentley_final_results_cleaned.txt
          git add bentley_final_results_cleaned.txt
          git commit -m "Cleaned wildcard domains in final results"
          git push
