name: Subdomain Recon Workflow for Tesco company

on: [push]

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Git and configure user
        run: |
          git config --global user.name "ASEEMYASH007"
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
      
      - name: Download Subfinder
        run: |
          mkdir -p /home/runner/configz/subfinder
          cp provider-config.yaml /home/runner/configz/subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.7/subfinder_2.6.7_linux_amd64.zip
          unzip subfinder_2.6.7_linux_amd64.zip
          sudo chmod +x subfinder
      - name: Run Subfinder
        run: |
          echo -e "tesco.com\nonestop.co.uk" > tesco_scope.txt
          ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -dL tesco_scope.txt -recursive -o tesco_subs.txt
          wc -l tesco_subs.txt
          git add tesco_subs.txt
          git commit -m 'Add Subfinder results for Tesco'
          git push
      - name: Run crtsh.py
        run: |
          python3 ./crtsh.py -d "tesco.com,onestop.co.uk" -r -w >> tesco_crtsh_domains.txt
          wc -l tesco_crtsh_domains.txt
          git add tesco_crtsh_domains.txt
          git commit -m 'Add crtsh.py results for Tesco'
          git push
      - name: Combine Subfinder and crtsh results
        run: |
          sort -u tesco_subs.txt tesco_crtsh_domains.txt > tesco_final1.txt
          wc -l tesco_final1.txt
          git add tesco_final1.txt
          git commit -m 'Combine Subfinder and crtsh results for Tesco'
          git push
      - name: Fetch Additional Sources
        run: |
          xargs -a tesco_scope.txt -I {} sh -c 'curl -s "https://jldc.me/anubis/subdomains/{}" | tr -d "[]\"" | tr "," "\n" >> jldc.txt'
          xargs -a tesco_scope.txt -I {} sh -c 'curl -s "https://api.subdomain.center/?domain={}" | tr -d "[]\"" | tr "," "\n" >> subcenter.txt'
          xargs -a tesco_scope.txt -I {} sh -c 'curl -s "https://api.hackertarget.com/hostsearch/?q={}" | cut -d"," -f1 >> hackertarget.txt'
          sudo chmod +x *
          ./alienvault_hostnamefetcher.sh "tesco.com,onestop.co.uk" tesco_alienvault.txt
          python3 ./merklemap2subscan.py -d tesco.com,onestop.co.uk -o tesco_merkle.txt
      - name: Combine Additional Source Results
        run: |
          sort -u subcenter.txt hackertarget.txt tesco_alienvault.txt jldc.txt tesco_merkle.txt > tesco_combined_domains.txt
          wc -l tesco_combined_domains.txt
          git add tesco_combined_domains.txt tesco_merkle.txt
          git commit -m 'Combine additional source results for Tesco'
          git push
      - name: Download Amazon Domains
        run: curl -o amazon_domains.TESCO.txt https://kaeferjaeger.gay/sni-ip-ranges/amazon/ipv4_merged_sni.txt

      - name: Download Oracle Domains
        run: curl -o oracle_domains.TESCO.txt https://kaeferjaeger.gay/sni-ip-ranges/oracle/ipv4_merged_sni.txt

      - name: Download DigitalOcean Domains
        run: curl -o digitalocean_domains.TESCO.txt https://kaeferjaeger.gay/sni-ip-ranges/digitalocean/ipv4_merged_sni.txt

      - name: Download Google Domains
        run: curl -o google_domains.TESCO.txt https://kaeferjaeger.gay/sni-ip-ranges/google/ipv4_merged_sni.txt

      - name: Download Microsoft Domains
        run: curl -o microsoft_domains.TESCO.txt https://kaeferjaeger.gay/sni-ip-ranges/microsoft/ipv4_merged_sni.txt

      - name: Concatenate All Domains
        run: cat amazon_domains.TESCO.txt oracle_domains.TESCO.txt digitalocean_domains.TESCO.txt google_domains.TESCO.txt microsoft_domains.TESCO.txt > all_domains.TESCO.txt

      - name: Filter for Specific Domains and Subdomains Entries
        run: |
          grep -Eo '\b(\S+\.)?(tesco\.com|onestop\.co\.uk)\b' all_domains.TESCO.txt | tr ' ' '\n' | sort -u > tesco_cloud_domains.txt
          wc -l tesco_cloud_domains.txt
      - name: Commit and Push Filtered Domains
        run: |
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
          git config --global user.name "ASEEMYASH007"
          git add tesco_cloud_domains.txt
          git commit -m "Add processed Tesco domains"
          git push
      - name: Combine All Results
        run: |
          sort -u tesco_final1.txt tesco_combined_domains.txt tesco_cloud_domains.txt > tesco_final_results.txt
          wc -l tesco_final_results.txt
          git add tesco_final_results.txt
          git commit -m 'Combine all results for Tesco'
          git push
      - name: Clean Wildcard Domains
        run: |
          sed 's/^\*\.\(.*\)$/\1/' tesco_final_results.txt > tesco_final_results_cleaned.txt
          wc -l tesco_final_results_cleaned.txt
          git add tesco_final_results_cleaned.txt
          git commit -m "Cleaned wildcard domains in final results"
          git push
