name: Subdomain Recon Workflow for teamsnap

on: [push]

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Git and configure user
        run: |
          git config --global user.name "ASEEMYASH007"
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
      
      - name: Download Subfinder
        run: |
          mkdir -p /home/runner/configz/subfinder
          cp provider-config.yaml /home/runner/configz/subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.7/subfinder_2.6.7_linux_amd64.zip
          unzip subfinder_2.6.7_linux_amd64.zip
          sudo chmod +x subfinder

      - name: Run Subfinder
        run: |
          echo -e "teamsnap.com" > teamsnap_scope.txt
          ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -dL teamsnap_scope.txt -recursive -o teamsnap_subs.txt
          wc -l teamsnap_subs.txt
          git add teamsnap_subs.txt
          git commit -m 'Add Subfinder results for teamsnap'
          git push

      - name: Run crtsh.py
        run: |
          python3 ./crtsh.py -d "teamsnap.com" -r -w >> teamsnap_crtsh_domains.txt
          wc -l teamsnap_crtsh_domains.txt
          git add teamsnap_crtsh_domains.txt
          git commit -m 'Add crtsh.py results for teamsnap'
          git push

      - name: Combine Subfinder and crtsh results
        run: |
          sort -u teamsnap_subs.txt teamsnap_crtsh_domains.txt > teamsnap_final1.txt
          wc -l teamsnap_final1.txt
          git add teamsnap_final1.txt
          git commit -m 'Combine Subfinder and crtsh results for teamsnap'
          git push

      - name: Fetch Additional Sources
        run: |
          xargs -a teamsnap_scope.txt -I {} sh -c 'curl -s "https://jldc.me/anubis/subdomains/{}" | tr -d "[]\"" | tr "," "\n" >> jldc.txt'
          xargs -a teamsnap_scope.txt -I {} sh -c 'curl -s "https://api.subdomain.center/?domain={}" | tr -d "[]\"" | tr "," "\n" >> subcenter.txt'
          xargs -a teamsnap_scope.txt -I {} sh -c 'curl -s "https://api.hackertarget.com/hostsearch/?q={}" | cut -d"," -f1 >> hackertarget.txt'
          sudo chmod +x *
          ./alienvault_hostnamefetcher.sh "teamsnap.com" teamsnap_alienvault.txt
          python3 ./merklemap2subscan.py -d teamsnap.com -o teamsnap_merkle.txt -t 5 -s

      - name: Combine Additional Source Results
        run: |
          sort -u subcenter.txt hackertarget.txt teamsnap_alienvault.txt jldc.txt teamsnap_merkle.txt > teamsnap_combined_domains.txt
          wc -l teamsnap_combined_domains.txt
          git add teamsnap_combined_domains.txt teamsnap_merkle.txt
          git commit -m 'Combine additional source results for teamsnap'
          git push

      - name: Download Amazon Domains
        run: curl -o amazon_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/amazon/ipv4_merged_sni.txt

      - name: Download Oracle Domains
        run: curl -o oracle_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/oracle/ipv4_merged_sni.txt

      - name: Download DigitalOcean Domains
        run: curl -o digitalocean_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/digitalocean/ipv4_merged_sni.txt

      - name: Download Google Domains
        run: curl -o google_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/google/ipv4_merged_sni.txt

      - name: Download Microsoft Domains
        run: curl -o microsoft_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/microsoft/ipv4_merged_sni.txt

      - name: Concatenate All Domains
        run: cat amazon_domains.NAYA.txt oracle_domains.NAYA.txt digitalocean_domains.NAYA.txt google_domains.NAYA.txt microsoft_domains.NAYA.txt > all_domains.NAYA.txt

      - name: Filter for Specific Domains and Subdomains Entries
        run: |
          grep -Eo '\b(\S+\.)?(teamsnap\.com)\b' all_domains.NAYA.txt | tr ' ' '\n' | sort -u > teamsnap_cloud_domains.txt
          wc -l teamsnap_cloud_domains.txt

      - name: Commit and Push Filtered Domains
        run: |
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
          git config --global user.name "ASEEMYASH007"
          git add teamsnap_cloud_domains.txt
          git commit -m "Add processed teamsnap domains"
          git push

      - name: Combine All Results
        run: |
          sort -u teamsnap_final1.txt teamsnap_combined_domains.txt teamsnap_cloud_domains.txt > teamsnap_final_results.txt
          wc -l teamsnap_final_results.txt
          git add teamsnap_final_results.txt
          git commit -m 'Combine all results for teamsnap'
          git push

      - name: Clean Wildcard Domains
        run: |
          sed 's/^\*\.\(.*\)$/\1/' teamsnap_final_results.txt > teamsnap_final_results_cleaned.txt
          wc -l teamsnap_final_results_cleaned.txt
          git add teamsnap_final_results_cleaned.txt
          git commit -m "Cleaned wildcard domains in final results"
          git push
