name: Subdomain Recon Workflow

on: [push]

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Git and configure user
        run: |
          git config --global user.name "ASEEMYASH007"
          git config --global user.email "21btrcc007@jainuniversity.ac.in"

      - name: Download Subfinder
        run: |
          mkdir -p /home/runner/configz/subfinder
          cp provider-config.yaml /home/runner/configz/subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.6/subfinder_2.6.6_linux_amd64.zip
          unzip subfinder_2.6.6_linux_amd64.zip
          sudo chmod +x *

      - name: Run subfinder
        run: |
          echo -e "moveworks.io\nmoveworks.ai" > moveworks_company_scope.txt
          ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -dL moveworks_company_scope.txt -o moveworks_company_subs.txt
          wc -l moveworks_company_subs.txt
          git add moveworks_company_subs.txt
          git commit -m 'Add subfinder results for Moveworks company'
          git push

      - name: Run crtsh.py
        run: |
          xargs -a moveworks_company_scope.txt -I {} python3 ./crtsh.py -d {} -r -w >> moveworks_company_crtsh_domains.txt
          wc -l moveworks_company_crtsh_domains.txt
          git add moveworks_company_crtsh_domains.txt
          git commit -m 'Add crtsh.py results for Moveworks company'
          git push

      - name: Combine subfinder and crtsh results
        run: |
          sort -u moveworks_company_subs.txt moveworks_company_crtsh_domains.txt > moveworks_company_final1.txt
          wc -l moveworks_company_final1.txt
          git add moveworks_company_final1.txt
          git commit -m 'Combine subfinder and crtsh results for Moveworks company'
          git push

      - name: Fetch additional sources
        run: |
          xargs -a moveworks_company_scope.txt -I {} sh -c 'curl -s "https://jldc.me/anubis/subdomains/{}" | tr -d "[]\"" | tr "," "\n" >> jldc.txt'
          xargs -a moveworks_company_scope.txt -I {} sh -c 'curl -s "https://api.subdomain.center/?domain={}" | tr -d "[]\"" | tr "," "\n" >> subcenter.txt'
          xargs -a moveworks_company_scope.txt -I {} sh -c 'curl -s "https://api.hackertarget.com/hostsearch/?q={}" | cut -d"," -f1 >> hackertarget.txt'
          sudo chmod +x *
          ./alienvault_hostnamefetcher.sh "moveworks.io,moveworks.ai" moveworks_company_alienvault.txt
          python3 ./merklemap2subscan.py -d moveworks.io,moveworks.ai -o moveworks_company_merkle.txt -t 5

      - name: Combine additional source results
        run: |
          sort -u subcenter.txt hackertarget.txt moveworks_company_alienvault.txt jldc.txt moveworks_company_merkle.txt > moveworks_company_combined_domains.txt
          wc -l moveworks_company_combined_domains.txt
          git add moveworks_company_combined_domains.txt moveworks_company_merkle.txt
          git commit -m 'Combine additional source results for Moveworks company'
          git push

      - name: Download Amazon domains
        run: curl -o amazon_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/amazon/ipv4_merged_sni.txt

      - name: Download Oracle domains
        run: curl -o oracle_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/oracle/ipv4_merged_sni.txt

      - name: Download DigitalOcean domains
        run: curl -o digitalocean_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/digitalocean/ipv4_merged_sni.txt

      - name: Download Google domains
        run: curl -o google_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/google/ipv4_merged_sni.txt

      - name: Download Microsoft domains
        run: curl -o microsoft_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/microsoft/ipv4_merged_sni.txt

      - name: Concatenate all domains
        run: cat amazon_domains.NAYA.txt oracle_domains.NAYA.txt digitalocean_domains.NAYA.txt google_domains.NAYA.txt microsoft_domains.NAYA.txt > all_domains.NAYA.txt

      - name: Filter for specific domains and subdomains entries
        run: |
          grep -Eo '\b(\S+\.)?(moveworks\.io|moveworks\.ai)\b' all_domains.NAYA.txt | sed 's/\[//g' | sed 's/\]//g' | tr ' ' '\n' > moveworks_company_cloud_domains.txt
          wc -l moveworks_company_cloud_domains.txt

      - name: Commit and push filtered domains
        run: |
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
          git config --global user.name "ASEEMYASH007"
          git add moveworks_company_cloud_domains.txt
          git commit -m "Add processed Moveworks company domains"
          git push

      - name: Combine all results
        run: |
          sort -u moveworks_company_final1.txt moveworks_company_combined_domains.txt moveworks_company_cloud_domains.txt > moveworks_company_final_results.txt
          wc -l moveworks_company_final_results.txt
          git add moveworks_company_final_results.txt
          git commit -m 'Combine all results for Moveworks company'
          git push
