name: Subdomain Recon Workflow

on: [push]

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Git and configure user
        run: |
          git config --global user.name "aseemyash"
          git config --global user.email "aseemyash98@gmail.com"

      - name: Download Subfinder
        run: |
          mkdir -p /home/runner/configz/subfinder
          cp provider-config.yaml /home/runner/configz/subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.6/subfinder_2.6.6_linux_amd64.zip
          unzip subfinder_2.6.6_linux_amd64.zip
          sudo chmod +x *

      - name: Run subfinder
        run: |
          echo -e "tomtom-global.com\ntomtom.com\ntomtomgroup.com" > tomtom_scope.txt
          ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -dL tomtom_scope.txt -o tomtom_subs.txt
          wc -l tomtom_subs.txt
          git add tomtom_subs.txt
          git commit -m 'Add subfinder results for TomTom'
          git push

      - name: Run crtsh.py
        run: |
          xargs -a tomtom_scope.txt -I {} python3 ./crtsh.py -d {} -r -w >> tomtom_crtsh_domains.txt
          wc -l tomtom_crtsh_domains.txt
          git add tomtom_crtsh_domains.txt
          git commit -m 'Add crtsh.py results for TomTom'
          git push

      - name: Combine subfinder and crtsh results
        run: |
          sort -u tomtom_subs.txt tomtom_crtsh_domains.txt > tomtom_final1.txt
          wc -l tomtom_final1.txt
          git add tomtom_final1.txt
          git commit -m 'Combine subfinder and crtsh results for TomTom'
          git push

      - name: Fetch additional sources
        run: |
          xargs -a tomtom_scope.txt -I {} sh -c 'curl -s "https://jldc.me/anubis/subdomains/{}" | tr -d "[]\"" | tr "," "\n" >> jldc.txt'
          xargs -a tomtom_scope.txt -I {} sh -c 'curl -s "https://api.subdomain.center/?domain={}" | tr -d "[]\"" | tr "," "\n" >> subcenter.txt'
          xargs -a tomtom_scope.txt -I {} sh -c 'curl -s "https://api.hackertarget.com/hostsearch/?q={}" | cut -d"," -f1 >> hackertarget.txt'
          sudo chmod +x *
          ./alienvault_hostnamefetcher.sh "tomtom-global.com,tomtom.com,tomtomgroup.com" tomtom_alienvault.txt
          python3 ./merklemap2subscan.py -d tomtom-global.com,tomtom.com,tomtomgroup.com -o tomtom_merkle.txt -t 5

      - name: Combine additional source results
        run: |
          sort -u subcenter.txt hackertarget.txt tomtom_alienvault.txt jldc.txt tomtom_merkle.txt > tomtom_combined_domains.txt
          wc -l tomtom_combined_domains.txt
          git add tomtom_combined_domains.txt tomtom_merkle.txt
          git commit -m 'Combine additional source results for TomTom'
          git push

      - name: Download Amazon domains
        run: curl -o amazon_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/amazon/ipv4_merged_sni.txt

      - name: Download Oracle domains
        run: curl -o oracle_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/oracle/ipv4_merged_sni.txt

      - name: Download DigitalOcean domains
        run: curl -o digitalocean_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/digitalocean/ipv4_merged_sni.txt

      - name: Download Google domains
        run: curl -o google_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/google/ipv4_merged_sni.txt

      - name: Download Microsoft domains
        run: curl -o microsoft_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/microsoft/ipv4_merged_sni.txt

      - name: Concatenate all domains
        run: cat amazon_domains.NAYA.txt oracle_domains.NAYA.txt digitalocean_domains.NAYA.txt google_domains.NAYA.txt microsoft_domains.NAYA.txt > all_domains.NAYA.txt

      - name: Filter for specific domains and subdomains entries
        run: |
          grep -Eo '\b(\S+\.)?(tomtom-global\.com|tomtom\.com|tomtomgroup\.com)\b' all_domains.NAYA.txt | sed 's/\[//g' | sed 's/\]//g' | tr ' ' '\n' > tomtom_cloud_domains.txt
          wc -l tomtom_cloud_domains.txt

      - name: Commit and push filtered domains
        run: |
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
          git config --global user.name "aseemyashuniversity"
          git add tomtom_cloud_domains.txt
          git commit -m "Add processed TomTom domains"
          git push

      - name: Combine all results
        run: |
          sort -u tomtom_final1.txt tomtom_combined_domains.txt tomtom_cloud_domains.txt > tomtom_final_results.txt
          wc -l tomtom_final_results.txt
          git add tomtom_final_results.txt
          git commit -m 'Combine all results for TomTom'
          git push
