name: Subdomain Recon Workflow

on: [push]

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Git user
        run: |
          git config --global user.email "aseemyash98@gmail.com"
          git config --global user.name "aseemyash"

      - name: Download Subfinder
        run: |
          mkdir -p /home/runner/configz/subfinder
          cp provider-config.yaml /home/runner/configz/subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.6/subfinder_2.6.6_linux_amd64.zip
          unzip subfinder_2.6.6_linux_amd64.zip

      - name: Make Subfinder executable
        run: sudo chmod +x subfinder

      - name: Run Subfinder and other sources
        run: |
          ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -d reuters.com | tee reuters_subs.txt
          wc -l reuters_subs.txt
          python3 ./crtsh.py -d reuters.com -r -w | tee -a crtsh_domains2.txt
          wc -l crtsh_domains2.txt
          sort -u reuters_subs.txt crtsh_domains2.txt > reuters_final1.txt
          wc -l reuters_final1.txt
          curl -s "https://jldc.me/anubis/subdomains/reuters.com" | tr -d '[]"' | tr ',' '\n' | tee -a jldc.txt
          curl -s "https://api.subdomain.center/?domain=reuters.com" | tr -d '[]"' | tr ',' '\n' | tee -a subcenter.txt
          curl -s "https://api.hackertarget.com/hostsearch/?q=reuters.com" | cut -d',' -f1 | tee -a hackertarget.txt
          curl -s "https://otx.alienvault.com/api/v1/indicators/domain/reuters.com/url_list?limit=10000&page=1" | jq -r '.url_list[].hostname' | tee -a alienvault.txt
          sort -u jldc.txt subcenter.txt hackertarget.txt alienvault.txt > new_domains.txt
          wc -l new_domains.txt
          sort -u reuters_final1.txt new_domains.txt > reuters_final.txt

      - name: view subdomain counts
        run: |
          wc -l reuters_final1.txt
          wc -l new_domains.txt
          wc -l reuters_final.txt

      - name: Save final subdomains
        run: |
          git config --global user.email "aseemyash98@gmail.com"
          git config --global user.name "aseemyash"
          git add reuters_final.txt
          git commit -m "Updated subdomains"
          git push

      # - name: Save Subfinder subdomains
      #   run: |
      #     chmod +x *
      #     ./csprecon -l reuters_final.txt | tee -a subs_extracted_by_csprecon.txt
      #     wc -l subs_extracted_by_csprecon.txt
      #     sort -u reuters_final.txt subs_extracted_by_csprecon.txt > full_final_reuterssubs.txt

      # - name: Save CSP recon subdomains
      #   run: |
      #     git config --global user.email "aseemyash98@gmail.com"
      #     git config --global user.name "aseemyash"
      #     git add subs_extracted_by_csprecon.txt full_final_reuterssubs.txt
      #     git commit -m "csp and final subdomains"
      #     git push

      - name: DNS brute force
        run: |
          git clone https://github.com/blechschmidt/massdns.git
          cd massdns
          make
          sudo make install
          cd ..
          wget https://wordlists-cdn.assetnote.io/data/manual/2m-subdomains.txt
          wget https://wordlists-cdn.assetnote.io/data/manual/best-dns-wordlist.txt
          wget https://gist.githubusercontent.com/jhaddix/f64c97d0863a78454e44c2f7119c2a6a/raw/96f4e51d96b2203f19f6381c8c545b278eaa0837/all.txt
          sort -u 2m-subdomains.txt best-dns-wordlist.txt all.txt > SUBBRUTE_all_in_one.txt
          wc -l SUBBRUTE_all_in_one.txt
          wget https://raw.githubusercontent.com/trickest/resolvers/main/resolvers-trusted.txt
          wget https://raw.githubusercontent.com/blechschmidt/massdns/master/lists/resolvers.txt
          sort -u resolvers-trusted.txt resolvers.txt > final_resolvers.txt
          chmod +x *
          ./puredns bruteforce SUBBRUTE_all_in_one.txt -d reuters_final.txt -r final_resolvers.txt | tee -a finaldnsbrute_reuters.txt

      - name: Save DNS brute force results
        run: |
          git config --global user.email "aseemyash98@gmail.com"
          git config --global user.name "aseemyash"
          git add finaldnsbrute_reuters.txt
          git commit -m "dnsbrute subdomains"
          git push
