name: Subdomain Recon Workflow

on: [push]

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure Git user
        run: |
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
          git config --global user.name "aseemyashuniversity"
      - name: Download Subfinder
        run: |
          mkdir -p /home/runner/configz/subfinder
          cp provider-config.yaml /home/runner/configz/subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.6/subfinder_2.6.6_linux_amd64.zip
          unzip subfinder_2.6.6_linux_amd64.zip
      - name: Make Subfinder executable
        run: sudo chmod +x *
      - name: Run Subfinder
        run: |
             ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -d sandbox.hexsafe.hextrust.com | tee hextrust.com_subssandbox.txt
             wc hextrust.com_subssandbox.txt -l
      - name: subdomain save subfinder
        run: |
           git config --global user.email "21btrcc007@jainuniversity.ac.in"
            git config --global user.name "aseemyashuniversity"
            git add hextrust.com_subssandbox.txt
            git commit -m "Updated subdomains"
            git push   
     
