name: Subdomain Recon Workflow for UK Ministry of Defense

on: [push]

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Git and configure user
        run: |
          git config --global user.name "ASEEMYASH007"
          git config --global user.email "21btrcc007@jainuniversity.ac.in"

      - name: Download Subfinder
        run: |
          mkdir -p /home/runner/configz/subfinder
          cp provider-config.yaml /home/runner/configz/subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.6/subfinder_2.6.6_linux_amd64.zip
          unzip subfinder_2.6.6_linux_amd64.zip
          sudo chmod +x *

      - name: Run subfinder
        run: |
          echo -e "mod.uk" > mod_uk_scope.txt
          ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -dL mod_uk_scope.txt -recursive -o mod_uk_subs.txt
          wc -l mod_uk_subs.txt
          git add mod_uk_subs.txt
          git commit -m 'Add subfinder results for UK Ministry of Defense'
          git push

      - name: Run crtsh.py
        run: |
          python3 ./crtsh.py -d "mod.uk" -r -w >> mod_uk_crtsh_domains.txt
          wc -l mod_uk_crtsh_domains.txt
          git add mod_uk_crtsh_domains.txt
          git commit -m 'Add crtsh.py results for UK Ministry of Defense'
          git push

      - name: Combine subfinder and crtsh results
        run: |
          sort -u mod_uk_subs.txt mod_uk_crtsh_domains.txt > mod_uk_final1.txt
          wc -l mod_uk_final1.txt
          git add mod_uk_final1.txt
          git commit -m 'Combine subfinder and crtsh results for UK Ministry of Defense'
          git push

      - name: Fetch additional sources
        run: |
          xargs -a mod_uk_scope.txt -I {} sh -c 'curl -s "https://jldc.me/anubis/subdomains/{}" | tr -d "[]\"" | tr "," "\n" >> jldc.txt'
          xargs -a mod_uk_scope.txt -I {} sh -c 'curl -s "https://api.subdomain.center/?domain={}" | tr -d "[]\"" | tr "," "\n" >> subcenter.txt'
          xargs -a mod_uk_scope.txt -I {} sh -c 'curl -s "https://api.hackertarget.com/hostsearch/?q={}" | cut -d"," -f1 >> hackertarget.txt'
          sudo chmod +x *
          ./alienvault_hostnamefetcher.sh "mod.uk" mod_uk_alienvault.txt
          python3 ./merklemap2subscan.py -d "mod.uk" -o mod_uk_merkle.txt -t 5

      - name: Combine additional source results
        run: |
          sort -u subcenter.txt hackertarget.txt mod_uk_alienvault.txt jldc.txt mod_uk_merkle.txt > mod_uk_combined_domains.txt
          wc -l mod_uk_combined_domains.txt
          git add mod_uk_combined_domains.txt mod_uk_merkle.txt
          git commit -m 'Combine additional source results for UK Ministry of Defense'
          git push

      - name: Download Amazon domains
        run: curl -o amazon_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/amazon/ipv4_merged_sni.txt

      - name: Download Oracle domains
        run: curl -o oracle_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/oracle/ipv4_merged_sni.txt

      - name: Download DigitalOcean domains
        run: curl -o digitalocean_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/digitalocean/ipv4_merged_sni.txt

      - name: Download Google domains
        run: curl -o google_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/google/ipv4_merged_sni.txt

      - name: Download Microsoft domains
        run: curl -o microsoft_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/microsoft/ipv4_merged_sni.txt

      - name: Concatenate all domains
        run: cat amazon_domains.NAYA.txt oracle_domains.NAYA.txt digitalocean_domains.NAYA.txt google_domains.NAYA.txt microsoft_domains.NAYA.txt > all_domains.NAYA.txt

      - name: Filter for specific domains and subdomains entries
        run: |
          grep -Eo '\b(\S+\.)?(mod\.uk)\b' all_domains.NAYA.txt | sed 's/\[//g' | sed 's/\]//g' | tr ' ' '\n' > mod_uk_cloud_domains.txt
          wc -l mod_uk_cloud_domains.txt

      - name: Commit and push filtered domains
        run: |
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
          git config --global user.name "ASEEMYASH007"
          git add mod_uk_cloud_domains.txt
          git commit -m "Add processed UK Ministry of Defense domains"
          git push

      - name: Combine all results
        run: |
          sort -u mod_uk_final1.txt mod_uk_combined_domains.txt mod_uk_cloud_domains.txt > mod_uk_final_results.txt
          wc -l mod_uk_final_results.txt
          git add mod_uk_final_results.txt
          git commit -m 'Combine all results for UK Ministry of Defense'
          git push

      - name: Clean wildcard domains
        run: |
          sed 's/^\*\.\(.*\)$/\1/' mod_uk_final_results.txt > mod_uk_final_results_cleaned.txt
          wc -l mod_uk_final_results_cleaned.txt
          git add mod_uk_final_results_cleaned.txt
          git commit -m "Cleaned wildcard domains in final results"
          git push
