name: Subdomain Recon Workflow

on: [push]

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Git and configure user
        run: |
          git config --global user.name "aseemyash"
          git config --global user.email "aseemyash98@gmail.com"

      - name: Download Subfinder
        run: |
          mkdir -p /home/runner/configz/subfinder
          cp provider-config.yaml /home/runner/configz/subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.6/subfinder_2.6.6_linux_amd64.zip
          unzip subfinder_2.6.6_linux_amd64.zip
          sudo chmod +x *

      - name: Run subfinder
        run: |
          #echo "mintel.com" > mintel.txt
          echo -e "mintel.com\nmintel.cloud\ncomperemedia.com\ngnpd.com" > mintel_scope.txt
          ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -dL mintel_scope.txt -o mintel_subs.txt
          wc -l mintel_subs.txt
          git add mintel_subs.txt
          git commit -m 'Add subfinder results'
          git push

      - name: Run crtsh.py
        run: |
          xargs -a mintel_scope.txt -I {} python3 ./crtsh.py -d {} -r -w >> mintel_crtsh_domains2.txt
          wc -l mintel_crtsh_domains2.txt
          git add mintel_crtsh_domains2.txt
          git commit -m 'Add crtsh.py results'
          git push

      - name: Combine subfinder and crtsh results
        run: |
          sort -u mintel_subs.txt mintel_crtsh_domains2.txt > mintel_final1.txt
          wc -l mintel_final1.txt
          git add mintel_final1.txt
          git commit -m 'Combine subfinder and crtsh results'
          git push

      - name: Fetch additional sources
        run: |
          #echo "mintel.com" > mintel.txt
          xargs -a mintel_scope.txt -I {} sh -c 'curl -s "https://jldc.me/anubis/subdomains/{}" | tr -d "[]\"" | tr "," "\n" >> jldc.txt'
          xargs -a mintel_scope.txt -I {} sh -c 'curl -s "https://api.subdomain.center/?domain={}" | tr -d "[]\"" | tr "," "\n" >> subcenter.txt'
          xargs -a mintel_scope.txt -I {} sh -c 'curl -s "https://api.hackertarget.com/hostsearch/?q={}" | cut -d"," -f1 >> hackertarget.txt'
          sudo chmod +x *
          ./alienvault_hostnamefetcher.sh "mintel.com,mintel.cloud,comperemedia.com,gnpd.com" mintel_alientvault.txt


      - name: Combine additional source results
        run: |
          sort -u subcenter.txt hackertarget.txt mintel_alientvault.txt jldc.txt > new_domains_mintel.txt
          wc -l new_domains_mintel.txt
          git add new_domains_mintel.txt
          git commit -m 'Combine additional source results'
          git push

      - name: Download Amazon domains
        run: curl -o amazon_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/amazon/ipv4_merged_sni.txt

      - name: Download Oracle domains
        run: curl -o oracle_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/oracle/ipv4_merged_sni.txt

      - name: Download DigitalOcean domains
        run: curl -o digitalocean_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/digitalocean/ipv4_merged_sni.txt

      - name: Download Google domains
        run: curl -o google_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/google/ipv4_merged_sni.txt

      - name: Download Microsoft domains
        run: curl -o microsoft_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/microsoft/ipv4_merged_sni.txt

      - name: Concatenate all domains
        run: cat amazon_domains.NAYA.txt oracle_domains.NAYA.txt digitalocean_domains.NAYA.txt google_domains.NAYA.txt microsoft_domains.NAYA.txt > all_domains.NAYA.txt

      - name: Filter for specific domains and subdomains entries
        run: |
          grep -Eo '\b(\S+\.)?(mintel\.com)\b' all_domains.NAYA.txt | sed 's/\[//g' | sed 's/\]//g' | tr ' ' '\n' > cloud_mintel_domains.NAYA.txt

      - name: Commit and push filtered domains
        run: |
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
          git config --global user.name "aseemyashuniversity"
          git add cloud_mintel_domains.NAYA.txt
          git commit -m "Add processed dlocal domains"
          git push

      - name: Combine all results
        run: |
          sort -u mintel_final1.txt new_domains_mintel.txt cloud_mintel_domains.NAYA.txt > mintel_final.txt
          wc -l mintel_final.txt
          git add mintel_final.txt
          git commit -m 'Combine all results'
          git push
