name: Subdomain Recon Workflow

on: [push]

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure Git user
        run: |
          git config --global user.email "aseemyash98@gmail.com"
          git config --global user.name "aseemyash"
      - name: Download Subfinder
        run: |
          mkdir -p /home/runner/configz/subfinder
          cp provider-config.yaml /home/runner/configz/subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.6/subfinder_2.6.6_linux_amd64.zip
          unzip subfinder_2.6.6_linux_amd64.zip
      - name: Make Subfinder executable
        run: sudo chmod +x *
      - name: Run Subfinder and crtsh
        run: |
             ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -d ford.com | tee ford_subs.txt
             wc ford_subs.txt -l
             python3 ./crtsh.py -d ford.com -r -w | tee -a crtsh_domains2.txt
             wc crtsh_domains2.txt -l
             sort -u ford_subs.txt crtsh_domains2.txt > ford_final.txt
             wc ford_final.txt -l
      
      - name: subdomain save final
        run: |
            git config --global user.email "aseemyash98@gmail.com"
            git config --global user.name "aseemyash"
            git add ford_final.txt
            git commit -m "Updated subdomains"
            git push   

      - name: subdomain save subfinder
        run: |
            
            chmod +x *
            ./csprecon -l ford_final.txt | tee -a subs_extracted_by_csprecon.txt
            wc subs_extracted_by_csprecon.txt -l
            sort -u ford_final.txt subs_extracted_by_csprecon.txt > full_final_fordsubs.txt

      - name: subdomain save csprecon
        run: |
           git config --global user.email "aseemyash98@gmail.com"
            git config --global user.name "aseemyash"
            git add subs_extracted_by_csprecon.txt full_final_fordsubs.txt
            git commit -m "csp and final subdomains"
            git push
      
      - name: DNS BRUTE
        run: |
            git clone https://github.com/blechschmidt/massdns.git
            cd massdns
            make
            sudo make install
            which massdns
            cd ..
            wget https://wordlists-cdn.assetnote.io/data/manual/2m-subdomains.txt
            wget https://wordlists-cdn.assetnote.io/data/manual/best-dns-wordlist.txt
            wget https://gist.githubusercontent.com/jhaddix/f64c97d0863a78454e44c2f7119c2a6a/raw/96f4e51d96b2203f19f6381c8c545b278eaa0837/all.txt
            sort -u 2m-subdomains.txt best-dns-wordlist.txt all.txt > SUBBRUTE_all_in_one.txt
            wc SUBBRUTE_all_in_one.txt -l
            wget https://raw.githubusercontent.com/trickest/resolvers/main/resolvers-trusted.txt
            wget https://raw.githubusercontent.com/blechschmidt/massdns/master/lists/resolvers.txt
            sort resolvers-trusted.txt resolvers.txt > final_resolvers.txt
            chmod +x *
            ./puredns bruteforce SUBBRUTE_all_in_one.txt -d ford_final.txt —r final_resolvers.txt | tee -a finaldnsbrute_ford.txt

      - name: subdomdnsbrute save
        run: |
           git config --global user.email "aseemyash98@gmail.com"
           git config --global user.name "aseemyash"
           git add finaldnsbrute_ford.txt
           git commit -m "dnsbrute subdomains"
           git push
