name: Subdomain Recon Workflow

on: [push]

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure Git user
        run: |
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
          git config --global user.name "aseemyashuniversity"
      - name: Download Subfinder
        run: |
          mkdir -p /home/runner/configz/subfinder
          cp provider-config.yaml /home/runner/configz/subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.6/subfinder_2.6.6_linux_amd64.zip
          unzip subfinder_2.6.6_linux_amd64.zip
      - name: Make Subfinder executable
        run: sudo chmod +x *
      - name: Run Subfinder
        run: |
             ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -d ford.com,lincoln.com,omnicraftautoparts.com,motorcraft.com,quicklane.com | tee ford_subs.txt
             wc ford_subs.txt -l
      - name: subdomain save subfinder
        run: |
           git config --global user.email "21btrcc007@jainuniversity.ac.in"
            git config --global user.name "aseemyashuniversity"
            git add ford_subs.txt
            git commit -m "Updated subdomains"
            git push   
      - name: dynamic subdomain enumeration with alterx
        run: |
          wget https://github.com/projectdiscovery/dnsx/releases/download/v1.2.1/dnsx_1.2.1_linux_amd64.zip
          unzip dnsx_1.2.1_linux_amd64.zip
          sudo chmod +x * 
          ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -dL ford_subs.txt | ./alterx | ./dnsx | tee final_subs_alter.txt
          sort -u final_subs_alter.txt -o ford_final_subs2.txt
          wc ford_final_subs2.txt -l
      - name: Commit subdomains file
        run: |
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
          git config --global user.name "aseemyashuniversity"
          git add ford_final_subs2.txt
          git commit -m "Updated subdomains"
          git push
