name: Subdomain Recon Workflow for Bundle Company

on: [push]

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Git and configure user
        run: |
          git config --global user.name "ASEEMYASH007"
          git config --global user.email "21btrcc007@jainuniversity.ac.in"

      - name: Download Subfinder
        run: |
          mkdir -p /home/runner/configz/subfinder
          cp provider-config.yaml /home/runner/configz/subfinder
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.6/subfinder_2.6.6_linux_amd64.zip
          unzip subfinder_2.6.6_linux_amd64.zip
          sudo chmod +x *

      - name: Run subfinder
        run: |
          echo -e "humblebundle.com" > bundle_company_scope.txt
          ./subfinder -pc "/home/runner/configz/subfinder/provider-config.yaml" -all -dL bundle_company_scope.txt -recursive -o bundle_company_subs.txt
          wc -l bundle_company_subs.txt
          git add bundle_company_subs.txt
          git commit -m 'Add subfinder results for Bundle company'
          git push

      - name: Run crtsh.py
        run: |
          python3 ./crtsh.py -d "humblebundle.com" -r -w >> bundle_company_crtsh_domains.txt
          wc -l bundle_company_crtsh_domains.txt
          git add bundle_company_crtsh_domains.txt
          git commit -m 'Add crtsh.py results for Bundle company'
          git push

      - name: Combine subfinder and crtsh results
        run: |
          sort -u bundle_company_subs.txt bundle_company_crtsh_domains.txt > bundle_final1.txt
          wc -l bundle_final1.txt
          git add bundle_final1.txt
          git commit -m 'Combine subfinder and crtsh results for Bundle company'
          git push

      - name: Fetch additional sources
        run: |
          xargs -a bundle_company_scope.txt -I {} sh -c 'curl -s "https://jldc.me/anubis/subdomains/{}" | tr -d "[]\"" | tr "," "\n" >> jldc.txt'
          xargs -a bundle_company_scope.txt -I {} sh -c 'curl -s "https://api.subdomain.center/?domain={}" | tr -d "[]\"" | tr "," "\n" >> subcenter.txt'
          xargs -a bundle_company_scope.txt -I {} sh -c 'curl -s "https://api.hackertarget.com/hostsearch/?q={}" | cut -d"," -f1 >> hackertarget.txt'
          sudo chmod +x *
          ./alienvault_hostnamefetcher.sh "humblebundle.com" bundle_company_alienvault.txt
          python3 ./merklemap2subscan.py -d "humblebundle.com" -o bundle_company_merkle.txt -t 5

      - name: Combine additional source results
        run: |
          sort -u subcenter.txt hackertarget.txt bundle_company_alienvault.txt jldc.txt bundle_company_merkle.txt > bundle_company_combined_domains.txt
          wc -l bundle_company_combined_domains.txt
          git add bundle_company_combined_domains.txt bundle_company_merkle.txt
          git commit -m 'Combine additional source results for Bundle company'
          git push

      - name: Download Amazon domains
        run: curl -o amazon_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/amazon/ipv4_merged_sni.txt

      - name: Download Oracle domains
        run: curl -o oracle_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/oracle/ipv4_merged_sni.txt

      - name: Download DigitalOcean domains
        run: curl -o digitalocean_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/digitalocean/ipv4_merged_sni.txt

      - name: Download Google domains
        run: curl -o google_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/google/ipv4_merged_sni.txt

      - name: Download Microsoft domains
        run: curl -o microsoft_domains.NAYA.txt https://kaeferjaeger.gay/sni-ip-ranges/microsoft/ipv4_merged_sni.txt

      - name: Concatenate all domains
        run: cat amazon_domains.NAYA.txt oracle_domains.NAYA.txt digitalocean_domains.NAYA.txt google_domains.NAYA.txt microsoft_domains.NAYA.txt > all_domains.NAYA.txt

      - name: Filter for specific domains and subdomains entries
        run: |
          grep -Eo '\b(\S+\.)?(humblebundle\.com)\b' all_domains.NAYA.txt | sed 's/\[//g' | sed 's/\]//g' | tr ' ' '\n' > bundle_company_cloud_domains.txt
          wc -l bundle_company_cloud_domains.txt

      - name: Commit and push filtered domains
        run: |
          git config --global user.email "21btrcc007@jainuniversity.ac.in"
          git config --global user.name "ASEEMYASH007"
          git add bundle_company_cloud_domains.txt
          git commit -m "Add processed Bundle company domains"
          git push

      - name: Combine all results
        run: |
          sort -u bundle_final1.txt bundle_company_combined_domains.txt bundle_company_cloud_domains.txt > bundle_company_final_results.txt
          wc -l bundle_company_final_results.txt
          git add bundle_company_final_results.txt
          git commit -m 'Combine all results for Bundle company'
          git push

      - name: Clean wildcard domains
        run: |
          sed 's/^\*\.\(.*\)$/\1/' bundle_company_final_results.txt > bundle_final_results_cleaned.txt
          wc -l bundle_final_results_cleaned.txt
          git add bundle_final_results_cleaned.txt
          git commit -m "Cleaned wildcard domains in final results"
          git push

      - name: Validate DNS records for subdomains
        run: |
          touch valid_bundle_subdomains.txt
          while read -r domain; do
            if host "$domain" &> /dev/null; then
              echo "$domain" >> valid_bundle_subdomains.txt
            fi
          done < bundle_final_results_cleaned.txt
          wc -l valid_bundle_subdomains.txt
          git add valid_bundle_subdomains.txt
          git commit -m "Add valid DNS subdomains for Bundle"
          git push
